### PR TITLE
Added icon in nav tab and in tab in broswer.

### PR DESCRIPTION
**Pull request by azaslavskis**
1) added correct titles
2) added the icon in png on top page and in nav bar
3) inverted color using css
Screenshot 2021-12-17 at 16 27 46

### CODE REVIEW

**Review by ed-ilyin — CHANGES_REQUESTED** [review]
Please remove .DS_Store файлс :)

**Comment by ed-ilyin** [comment]
Why so many logo files everywhere? :D
image

**Comment by azaslavskis** [comment]
Fixed .. just my finding to find where the logo files should be .. ^)

**Comment by ed-ilyin** [comment]
Still couple of DS files: 
image

**Review by ed-ilyin — APPROVED** [review]

**Pull request merged**
